"""Run management tables: Runs, allocation results, and chat history."""

from datetime import datetime
from decimal import Decimal
from typing import Optional, List
from enum import Enum as PyEnum

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Numeric, JSON, Enum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.db.base import Base, TimestampMixin


class RunStatus(str, PyEnum):
    """Status of a generation run."""
    PENDING = "pending"
    MATCHING = "matching"  # Stage 1: Competitor matching
    AWAITING_CONFIRMATION = "awaiting_confirmation"  # Stage 1.5: User confirmation
    GENERATING = "generating"  # Stage 2: LLM generation
    PARSING = "parsing"  # Stage 3: Output parsing
    FEEDBACK = "feedback"  # Stage 4: Feedback generation
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Run(Base, TimestampMixin):
    """Generation run state and inputs.

    Tracks the lifecycle of a budget allocation generation request,
    from initial input through all pipeline stages to completion.
    """

    __tablename__ = "runs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Session context
    session_token: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    user_id: Mapped[Optional[int]] = mapped_column(ForeignKey("users.id"), nullable=True)
    project_id: Mapped[Optional[int]] = mapped_column(ForeignKey("projects.id"), nullable=True)
    project_version_id: Mapped[Optional[int]] = mapped_column(ForeignKey("project_versions.id"), nullable=True)

    # Input parameters
    customer_name: Mapped[str] = mapped_column(String(255), nullable=False)
    industry: Mapped[str] = mapped_column(String(255), nullable=False)
    brand_kpi: Mapped[str] = mapped_column(String(50), nullable=False)  # adaware, aided, consider
    total_budget: Mapped[Optional[Decimal]] = mapped_column(Numeric(15, 2), nullable=True)
    time_period_start: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    time_period_end: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Additional input parameters (stored as JSON)
    input_parameters: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Run status
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=RunStatus.PENDING.value,
        index=True
    )

    # Timestamps for each stage
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Error tracking
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Input hash for caching (detect unchanged inputs)
    input_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)

    # Matched competitors (stored after confirmation)
    confirmed_competitors: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Relationships
    user: Mapped[Optional["User"]] = relationship("User", back_populates="runs")
    project: Mapped[Optional["Project"]] = relationship("Project", back_populates="runs")
    allocation_result: Mapped[Optional["AllocationResult"]] = relationship(
        "AllocationResult", back_populates="run", uselist=False
    )
    chat_history: Mapped[List["ChatHistory"]] = relationship("ChatHistory", back_populates="run")
    prompt_traces: Mapped[List["PromptTrace"]] = relationship("PromptTrace", back_populates="run")


class AllocationResult(Base, TimestampMixin):
    """LLM output storage for budget allocations.

    Stores the parsed and validated allocation recommendations
    generated by the LLM.
    """

    __tablename__ = "allocation_results"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Link to run
    run_id: Mapped[int] = mapped_column(ForeignKey("runs.id"), nullable=False, unique=True, index=True)

    # Allocation data (JSON structure)
    # Format: {"channels": [{"name": "TV", "percentage": 35.0, "amount": 350000}, ...]}
    allocations: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Summary text generated by LLM
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Confidence score (0-1)
    confidence_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)

    # Raw LLM response (for debugging)
    raw_response: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Validation status
    is_valid: Mapped[bool] = mapped_column(default=True, nullable=False)
    validation_errors: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Relationship
    run: Mapped["Run"] = relationship("Run", back_populates="allocation_result")


class ChatHistory(Base, TimestampMixin):
    """Feedback cards for the chat interface.

    Stores generated feedback messages including warnings, alerts,
    and recommendations that are displayed to the user.
    """

    __tablename__ = "chat_history"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Link to run
    run_id: Mapped[int] = mapped_column(ForeignKey("runs.id"), nullable=False, index=True)

    # Message type (warning, alert, summary, recommendation)
    message_type: Mapped[str] = mapped_column(String(50), nullable=False)

    # Severity (info, warning, error)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")

    # Message content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # Additional data (renamed from 'metadata' - reserved in SQLAlchemy)
    extra_data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Order for display
    display_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Relationship
    run: Mapped["Run"] = relationship("Run", back_populates="chat_history")


# Import for type hints
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from src.db.models.shared import User, Project
    from src.db.models.prompt import PromptTrace
